# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            Vaginale Lasertheraphie
tagline:          'Vaginale Lasertheraphie'
description:      'SEMINAR'
baseurl: "/vaginale_laserbehandlung/" # the subpath of your site, e.g. /blog
url: "https://juliafleckenstein.github.io/vaginale_Laserbehandlung/" # the base hostname & protocol for your site, e.g. http://example.com

paginate:         5

# Custom vars
#version:          2.1.0

github:
  repo:           https://github.com/JuliaFleckenstein/vaginale_Laserbehandlung

plugins:
  - jekyll-feed

collections:
  sessions:
    output: true
